spring:
  application:
    name: "discovery-service"

server:
  port: 8888

eureka:
  instance:
    hostname: "discovery-service"
  client:
    service-url:
      defaultZone: "http://discovery-service:8888/eureka/"
    register-with-eureka: false
    fetch-registry: false