#ortama göre(dev local prod) değişkenlk gösterenler config içine alındı.
configurl: http://localhost:8079
spring:
  application:
    name: "orderservice"

  cloud:
    config:
      profile: local #nerede çalısacağını belirler, burada localde çalışırken, compose içinde dev de çalışır.

  config:
    import: configserver:${configurl} #config server yolu, tekil old icin değismesine gerek yoktur.