spring:
  application:
    name: "order-service"

  cloud:
    stream:
      defaultBinder: kafka
      function:
        definition: orderCreatedFunction
      bindings:
        orderCreatedFunction-out-0:
          destination: order-topic
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092

  datasource:
    url: "jdbc:postgresql://localhost:5435/order-service"
    username: postgres
    password: test

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hibernate:
      ddl-auto: update

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true