spring:
  application:
    name: "cart-service"

  cloud:
    stream:
      defaultBinder: kafka
      function:
        definition: orderCreatedFunction
      bindings:
        orderCreatedFunction-in-0:
          destination: order-topic
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092

  data:
    mongodb:
      uri: mongodb://admin:test@localhost:27020/cart-service?authSource=admin

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

